/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    services: Service;
    industries: Industry;
    team: Team;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Se genera automáticamente. Ej: reforma-tributaria-2025
   */
  slug: string;
  /**
   * Máximo 160 caracteres para SEO óptimo
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  category?: ('tributario' | 'laboral' | 'contable' | 'financiero' | 'empresarial') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | Team;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * Texto breve para tarjetas de equipo en el landing.
   */
  summary?: string | null;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Marca solo a la persona que aparece como fundadora en /nosotros y en el home
   */
  isFounder?: boolean | null;
  /**
   * Bloques que aparecen en la página /nosotros
   */
  credentials?:
    | {
        icon?: ('GraduationCap' | 'Certificate' | 'Desktop') | null;
        label: string;
        value: string;
        sub?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Chips simples que aparecen en la sección Fundadora del home
   */
  shortCredentials?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  linkedin?: string | null;
  email?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  /**
   * Número decorativo que aparece en la tarjeta
   */
  number?: string | null;
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: ('BookOpen' | 'Users' | 'CurrencyDollar' | 'Briefcase' | 'MagnifyingGlass' | 'Scales') | null;
  /**
   * Bullets que se muestran en la página de detalle del servicio
   */
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  slug: string;
  icon?: ('Flask' | 'ShoppingCart' | 'Scales' | 'GraduationCap' | 'DotsThreeCircle') | null;
  /**
   * Texto descriptivo que aparece en la sección completa
   */
  descriptionLong?: string | null;
  /**
   * Texto corto para el panel interactivo del home
   */
  descriptionShort?: string | null;
  services?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Campo legado; se usa solo si descriptionLong está vacío
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Imagen visible en el perfil y la esquina superior del panel.
   */
  avatar?: (number | null) | Media;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  category?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  number?: T;
  shortDescription?: T;
  fullDescription?: T;
  icon?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  descriptionLong?: T;
  descriptionShort?: T;
  services?:
    | T
    | {
        text?: T;
        id?: T;
      };
  description?: T;
  image?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  summary?: T;
  photo?: T;
  bio?: T;
  isFounder?: T;
  credentials?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        sub?: T;
        id?: T;
      };
  shortCredentials?:
    | T
    | {
        text?: T;
        id?: T;
      };
  linkedin?: T;
  email?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  emailSecondary?: string | null;
  address?: string | null;
  /**
   * Sin + ni espacios. Ej: 593999828903
   */
  whatsappNumber?: string | null;
  /**
   * Agrega, ordena u oculta redes sociales sin tocar código. Si esta lista queda vacía, se usan Instagram y LinkedIn como respaldo.
   */
  socialLinks?:
    | {
        platform: 'instagram' | 'linkedin' | 'facebook' | 'youtube' | 'tiktok' | 'x' | 'whatsapp' | 'website';
        /**
         * Opcional. Si queda vacía se usa el nombre de la red.
         */
        label?: string | null;
        url: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  instagram?: string | null;
  linkedin?: string | null;
  /**
   * Máximo 160 caracteres
   */
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  googleVerification?: string | null;
  heroBadge?: string | null;
  /**
   * Usa la variable {highlight} para marcar la palabra que irá en coral cursiva
   */
  heroTitle?: string | null;
  heroHighlight?: string | null;
  heroSubtitle?: string | null;
  heroMediaMode?: ('video' | 'image' | 'abstract') | null;
  /**
   * Ej: /assets/media/hero-atenea.mp4. El video se reproduce sin audio.
   */
  heroVideoSrc?: string | null;
  /**
   * Imagen de respaldo para carga lenta o mobile. Ej: /assets/media/hero-atenea-poster.jpg
   */
  heroPosterSrc?: string | null;
  /**
   * Se usa cuando el modo del hero es Imagen humana.
   */
  heroBackgroundImageSrc?: string | null;
  /**
   * 0 = sin oscurecer, 0.92 = muy oscuro. Recomendado: 0.28 a 0.38 para video.
   */
  heroOverlayOpacity?: number | null;
  heroShowFinancialOverlay?: boolean | null;
  heroCtaPrimaryLabel?: string | null;
  heroCtaPrimaryHref?: string | null;
  heroCtaSecondaryLabel?: string | null;
  heroCtaSecondaryHref?: string | null;
  heroEspecialidades?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  heroCredits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  quienesSomosText?: string | null;
  valores?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        /**
         * Si no subes imagen, se usa esta URL
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  razonesTitle?: string | null;
  razones?:
    | {
        icon?: ('ArrowsLeftRight' | 'Clock' | 'Lightbulb' | 'Lock' | 'Handshake') | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  teamSectionMode?: ('founder' | 'team') | null;
  teamSectionEyebrow?: string | null;
  teamSectionTitle?: string | null;
  teamSectionDescription?: string | null;
  /**
   * Párrafos de la sección Fundadora en el home
   */
  fundadoraBioShort?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  nosotrosMissionTitle?: string | null;
  nosotrosMissionParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  nosotrosValores?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  fundadoraBioLong?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  servicesPageEyebrow?: string | null;
  servicesPageTitle?: string | null;
  servicesPageDescription?: string | null;
  servicesCardLinkLabel?: string | null;
  servicesCtaTitle?: string | null;
  servicesCtaDescription?: string | null;
  servicesCtaLabel?: string | null;
  servicesCtaHref?: string | null;
  serviceDetailBackLabel?: string | null;
  serviceDetailIncludesTitle?: string | null;
  serviceDetailCtaTitle?: string | null;
  serviceDetailCtaDescription?: string | null;
  serviceDetailCtaLabel?: string | null;
  serviceDetailPhoneLabel?: string | null;
  serviceDetailMoreLabel?: string | null;
  serviceDetailMoreLinkLabel?: string | null;
  industriesPageEyebrow?: string | null;
  industriesPageTitle?: string | null;
  industriesPageDescription?: string | null;
  industriesCtaEyebrow?: string | null;
  industriesCtaTitle?: string | null;
  industriesCtaDescription?: string | null;
  industriesCtaLabel?: string | null;
  industriesCtaHref?: string | null;
  newsPageEyebrow?: string | null;
  newsPageTitle?: string | null;
  newsPageDescription?: string | null;
  newsEmptyTitle?: string | null;
  newsEmptyText?: string | null;
  newsReadLabel?: string | null;
  newsReadMoreLabel?: string | null;
  newsDetailBackLabel?: string | null;
  newsDetailCtaTitle?: string | null;
  newsDetailCtaDescription?: string | null;
  newsDetailCtaLabel?: string | null;
  newsDetailContactLabel?: string | null;
  newsDetailMoreLabel?: string | null;
  newsDetailBackToListLabel?: string | null;
  contactPageEyebrow?: string | null;
  contactPageTitle?: string | null;
  contactPageDescription?: string | null;
  contactInfoTitle?: string | null;
  contactAddressLabel?: string | null;
  contactPhoneLabel?: string | null;
  contactEmailLabel?: string | null;
  contactSocialLabel?: string | null;
  contactFormTitle?: string | null;
  privacyEyebrow?: string | null;
  privacyTitle?: string | null;
  privacyIntro?: string | null;
  privacySections?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  privacyUpdatedAtLabel?: string | null;
  footerDescription?: string | null;
  footerPreCtaEyebrow?: string | null;
  footerPreCtaTitle?: string | null;
  footerPreCtaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  portalLabel?: string | null;
  portalHref?: string | null;
  footerCompanyItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  phone?: T;
  email?: T;
  emailSecondary?: T;
  address?: T;
  whatsappNumber?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        order?: T;
        id?: T;
      };
  instagram?: T;
  linkedin?: T;
  metaDescription?: T;
  ogImage?: T;
  googleVerification?: T;
  heroBadge?: T;
  heroTitle?: T;
  heroHighlight?: T;
  heroSubtitle?: T;
  heroMediaMode?: T;
  heroVideoSrc?: T;
  heroPosterSrc?: T;
  heroBackgroundImageSrc?: T;
  heroOverlayOpacity?: T;
  heroShowFinancialOverlay?: T;
  heroCtaPrimaryLabel?: T;
  heroCtaPrimaryHref?: T;
  heroCtaSecondaryLabel?: T;
  heroCtaSecondaryHref?: T;
  heroEspecialidades?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroCredits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        detail?: T;
        id?: T;
      };
  quienesSomosText?: T;
  valores?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  razonesTitle?: T;
  razones?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  teamSectionMode?: T;
  teamSectionEyebrow?: T;
  teamSectionTitle?: T;
  teamSectionDescription?: T;
  fundadoraBioShort?:
    | T
    | {
        text?: T;
        id?: T;
      };
  nosotrosMissionTitle?: T;
  nosotrosMissionParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  nosotrosValores?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  fundadoraBioLong?:
    | T
    | {
        text?: T;
        id?: T;
      };
  servicesPageEyebrow?: T;
  servicesPageTitle?: T;
  servicesPageDescription?: T;
  servicesCardLinkLabel?: T;
  servicesCtaTitle?: T;
  servicesCtaDescription?: T;
  servicesCtaLabel?: T;
  servicesCtaHref?: T;
  serviceDetailBackLabel?: T;
  serviceDetailIncludesTitle?: T;
  serviceDetailCtaTitle?: T;
  serviceDetailCtaDescription?: T;
  serviceDetailCtaLabel?: T;
  serviceDetailPhoneLabel?: T;
  serviceDetailMoreLabel?: T;
  serviceDetailMoreLinkLabel?: T;
  industriesPageEyebrow?: T;
  industriesPageTitle?: T;
  industriesPageDescription?: T;
  industriesCtaEyebrow?: T;
  industriesCtaTitle?: T;
  industriesCtaDescription?: T;
  industriesCtaLabel?: T;
  industriesCtaHref?: T;
  newsPageEyebrow?: T;
  newsPageTitle?: T;
  newsPageDescription?: T;
  newsEmptyTitle?: T;
  newsEmptyText?: T;
  newsReadLabel?: T;
  newsReadMoreLabel?: T;
  newsDetailBackLabel?: T;
  newsDetailCtaTitle?: T;
  newsDetailCtaDescription?: T;
  newsDetailCtaLabel?: T;
  newsDetailContactLabel?: T;
  newsDetailMoreLabel?: T;
  newsDetailBackToListLabel?: T;
  contactPageEyebrow?: T;
  contactPageTitle?: T;
  contactPageDescription?: T;
  contactInfoTitle?: T;
  contactAddressLabel?: T;
  contactPhoneLabel?: T;
  contactEmailLabel?: T;
  contactSocialLabel?: T;
  contactFormTitle?: T;
  privacyEyebrow?: T;
  privacyTitle?: T;
  privacyIntro?: T;
  privacySections?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  privacyUpdatedAtLabel?: T;
  footerDescription?: T;
  footerPreCtaEyebrow?: T;
  footerPreCtaTitle?: T;
  footerPreCtaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  portalLabel?: T;
  portalHref?: T;
  footerCompanyItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}