import {
  LexicalDiffComponent,
  RscEntryLexicalCell,
  RscEntryLexicalField,
} from '@payloadcms/richtext-lexical/rsc'
import {
  AlignFeatureClient,
  BlockquoteFeatureClient,
  BoldFeatureClient,
  ChecklistFeatureClient,
  HeadingFeatureClient,
  HorizontalRuleFeatureClient,
  IndentFeatureClient,
  InlineCodeFeatureClient,
  InlineToolbarFeatureClient,
  ItalicFeatureClient,
  LinkFeatureClient,
  OrderedListFeatureClient,
  ParagraphFeatureClient,
  RelationshipFeatureClient,
  StrikethroughFeatureClient,
  SubscriptFeatureClient,
  SuperscriptFeatureClient,
  UnderlineFeatureClient,
  UnorderedListFeatureClient,
  UploadFeatureClient,
} from '@payloadcms/richtext-lexical/client'
import {
  MetaDescriptionComponent,
  MetaImageComponent,
  MetaTitleComponent,
  OverviewComponent,
  PreviewComponent,
} from '@payloadcms/plugin-seo/client'
import {
  CollectionCards as CollectionCards_rsc,
  DefaultNav as DefaultNav_rsc,
  DocumentHeader as DocumentHeader_rsc,
  FolderField as FolderField_rsc,
  FolderTableCell as FolderTableCell_rsc,
  Logo as Logo_rsc,
} from '@payloadcms/next/rsc'
import { AteneaAdminLogo } from '@/components/payload/AteneaAdminLogo'
import { AteneaDashboardIntro } from '@/components/payload/AteneaDashboardIntro'
import { AteneaLoginIntro } from '@/components/payload/AteneaLoginIntro'
import { AteneaLogoutButton } from '@/components/payload/AteneaLogoutButton'
import { AteneaColorField, AteneaThemePalette } from '@/components/payload/AteneaThemePalette'
import { AteneaUserAvatar } from '@/components/payload/AteneaUserAvatar'

export const importMap = {
  '@payloadcms/richtext-lexical/rsc#RscEntryLexicalCell': RscEntryLexicalCell,
  '@payloadcms/richtext-lexical/rsc#RscEntryLexicalField': RscEntryLexicalField,
  '@payloadcms/richtext-lexical/rsc#LexicalDiffComponent': LexicalDiffComponent,
  '@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient': InlineToolbarFeatureClient,
  '@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient': HorizontalRuleFeatureClient,
  '@payloadcms/richtext-lexical/client#UploadFeatureClient': UploadFeatureClient,
  '@payloadcms/richtext-lexical/client#BlockquoteFeatureClient': BlockquoteFeatureClient,
  '@payloadcms/richtext-lexical/client#RelationshipFeatureClient': RelationshipFeatureClient,
  '@payloadcms/richtext-lexical/client#LinkFeatureClient': LinkFeatureClient,
  '@payloadcms/richtext-lexical/client#ChecklistFeatureClient': ChecklistFeatureClient,
  '@payloadcms/richtext-lexical/client#OrderedListFeatureClient': OrderedListFeatureClient,
  '@payloadcms/richtext-lexical/client#UnorderedListFeatureClient': UnorderedListFeatureClient,
  '@payloadcms/richtext-lexical/client#IndentFeatureClient': IndentFeatureClient,
  '@payloadcms/richtext-lexical/client#AlignFeatureClient': AlignFeatureClient,
  '@payloadcms/richtext-lexical/client#HeadingFeatureClient': HeadingFeatureClient,
  '@payloadcms/richtext-lexical/client#ParagraphFeatureClient': ParagraphFeatureClient,
  '@payloadcms/richtext-lexical/client#InlineCodeFeatureClient': InlineCodeFeatureClient,
  '@payloadcms/richtext-lexical/client#SuperscriptFeatureClient': SuperscriptFeatureClient,
  '@payloadcms/richtext-lexical/client#SubscriptFeatureClient': SubscriptFeatureClient,
  '@payloadcms/richtext-lexical/client#StrikethroughFeatureClient': StrikethroughFeatureClient,
  '@payloadcms/richtext-lexical/client#UnderlineFeatureClient': UnderlineFeatureClient,
  '@payloadcms/richtext-lexical/client#BoldFeatureClient': BoldFeatureClient,
  '@payloadcms/richtext-lexical/client#ItalicFeatureClient': ItalicFeatureClient,
  '@payloadcms/plugin-seo/client#OverviewComponent': OverviewComponent,
  '@payloadcms/plugin-seo/client#MetaTitleComponent': MetaTitleComponent,
  '@payloadcms/plugin-seo/client#MetaDescriptionComponent': MetaDescriptionComponent,
  '@payloadcms/plugin-seo/client#MetaImageComponent': MetaImageComponent,
  '@payloadcms/plugin-seo/client#PreviewComponent': PreviewComponent,
  '@/components/payload/AteneaAdminLogo#AteneaAdminLogo': AteneaAdminLogo,
  '@/components/payload/AteneaThemePalette#AteneaColorField': AteneaColorField,
  '@/components/payload/AteneaThemePalette#AteneaThemePalette': AteneaThemePalette,
  '@/components/payload/AteneaDashboardIntro#AteneaDashboardIntro': AteneaDashboardIntro,
  '@/components/payload/AteneaLoginIntro#AteneaLoginIntro': AteneaLoginIntro,
  '@/components/payload/AteneaLogoutButton#AteneaLogoutButton': AteneaLogoutButton,
  '@/components/payload/AteneaUserAvatar#AteneaUserAvatar': AteneaUserAvatar,
  '@payloadcms/next/rsc#CollectionCards': CollectionCards_rsc,
  '@payloadcms/next/rsc#DefaultNav': DefaultNav_rsc,
  '@payloadcms/next/rsc#DocumentHeader': DocumentHeader_rsc,
  '@payloadcms/next/rsc#FolderField': FolderField_rsc,
  '@payloadcms/next/rsc#FolderTableCell': FolderTableCell_rsc,
  '@payloadcms/next/rsc#Logo': Logo_rsc,
}
